"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function TermsPage() {
  const router = useRouter();
  const [language, setLanguage] = useState("en"); // 'en' or 'pl'

  return (
    <div className="max-w-4xl mx-auto p-8 text-left">
      {/* Back button and language switcher */}
      <div className="mb-6 flex justify-between items-center">
        <button
          onClick={() => router.back()}
          className="flex items-center text-gray-700 hover:text-blue-600"
        >
          ← Back
        </button>
        
        <div className="flex gap-2">
          <button
            onClick={() => setLanguage("en")}
            className={`px-4 py-2 rounded-lg font-semibold transition ${
              language === "en"
                ? "bg-blue-600 text-white"
                : "bg-gray-200 text-gray-700 hover:bg-gray-300"
            }`}
          >
            🇬🇧 English
          </button>
          <button
            onClick={() => setLanguage("pl")}
            className={`px-4 py-2 rounded-lg font-semibold transition ${
              language === "pl"
                ? "bg-blue-600 text-white"
                : "bg-gray-200 text-gray-700 hover:bg-gray-300"
            }`}
          >
            🇵🇱 Polski
          </button>
        </div>
      </div>

      {/* English Version */}
      {language === "en" && (
        <div className="prose prose-lg max-w-none">
          <h1 className="text-3xl font-bold mb-4">🇬🇧 Terms of Use</h1>
          <p className="text-sm text-gray-600 mb-8"><strong>Last updated:</strong> 14 October 2025</p>

          <p className="mb-6">
            Welcome to <strong>Flow-XR</strong>, a web application operated by <strong>Flow System Adam Grono</strong>, offering AI-assisted coaching sessions in the areas of personal development, spirituality, leadership, and related topics ("the App").
          </p>
          <p className="mb-6">
            By using this App, you agree to these Terms of Use. Please read them carefully before accessing or using any part of the App.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">1. Definitions</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li><strong>App</strong> – the Flow-XR web application available at <a href="https://flow-xr.com" className="text-blue-600 underline">https://flow-xr.com</a>.</li>
            <li><strong>User / You</strong> – any person accessing or using the App, whether registered or as a guest.</li>
            <li><strong>Account</strong> – a user account created via email or Google OAuth login.</li>
            <li><strong>AI Services</strong> – responses or interactions generated by external artificial intelligence models (e.g., OpenAI).</li>
            <li><strong>We / Us / Provider</strong> – Flow System Adam Grono, Lesoka 2/4, 81-574 Gdynia, Poland, <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-8 mb-4">2. Acceptance of Terms</h2>
          <p className="mb-4">By accessing or using the App, you confirm that you:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>have read and understood these Terms of Use,</li>
            <li>agree to comply with them,</li>
            <li>are at least 18 years old or have legal capacity to enter into binding agreements.</li>
          </ul>
          <p className="mb-6">If you do not agree with these Terms, you must not use the App.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">3. Description of Services</h2>
          <p className="mb-4">
            Flow-XR provides AI-assisted coaching experiences designed to support self-development, reflection, and personal growth.
            Some features may require account registration or authentication via Google OAuth.
          </p>
          <p className="mb-4">The App may include:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>interactive chat sessions with AI,</li>
            <li>progress tracking,</li>
            <li>saved session history,</li>
            <li>user reflections or notes.</li>
          </ul>
          <p className="mb-6">
            Flow-XR is <strong>not a substitute for professional therapy, medical advice, or counseling</strong>. It serves exclusively educational, reflective, and developmental purposes.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">4. User Responsibilities</h2>
          <p className="mb-4">You agree to:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>use the App lawfully and respectfully,</li>
            <li>not share illegal, offensive, or harmful content,</li>
            <li>not use the App for marketing, spamming, or automated scraping,</li>
            <li>keep your login credentials secure,</li>
            <li>use your own data responsibly, avoiding sensitive or confidential information.</li>
          </ul>
          <p className="mb-6">You are responsible for all activity conducted under your account.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">5. AI-Generated Content Disclaimer</h2>
          <p className="mb-4">
            The App uses publicly available AI models (e.g., OpenAI) to generate coaching dialogue.
            While the AI is designed to be supportive and inspiring, its responses:
          </p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>are generated automatically,</li>
            <li>may be incomplete, inaccurate, or subjective,</li>
            <li>do not constitute professional, medical, psychological, or legal advice.</li>
          </ul>
          <p className="mb-6">
            We recommend using your own judgment when interpreting AI responses. Flow-XR is not liable for decisions made based on AI-generated content.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">6. Account Registration and Security</h2>
          <p className="mb-4">Users may register using:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>email and password, or</li>
            <li>Google OAuth authentication.</li>
          </ul>
          <p className="mb-4">You agree to:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>provide accurate and current information,</li>
            <li>protect your account credentials,</li>
            <li>immediately report any unauthorized use to <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>.</li>
          </ul>
          <p className="mb-6">We reserve the right to suspend or delete accounts that violate these Terms or applicable laws.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">7. Guest Users</h2>
          <p className="mb-6">
            Guest users may access limited features of the App without creating an account.
            Guest progress is identified via a temporary ID stored in the browser's <strong>localStorage</strong>.
            This data is not linked to personally identifiable information and can be deleted by the user at any time.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">8. Intellectual Property</h2>
          <p className="mb-6">
            All materials within the App, including text, design, branding, code, and visual assets, are the property of <strong>Flow System Adam Grono</strong> or its licensors.
          </p>
          <p className="mb-6">
            Users may use the App solely for personal, non-commercial purposes.
            Reproduction, distribution, modification, or reverse engineering of the App or its components is prohibited without written consent.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">9. Privacy and Data Protection</h2>
          <p className="mb-6">
            Use of the App is governed by our <a href="/privacy" className="text-blue-600 underline">Privacy Policy</a>.
            By using the App, you consent to the processing of your personal data in accordance with that policy.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">10. Availability and Modifications</h2>
          <p className="mb-6">
            We aim to ensure the App operates reliably but do not guarantee uninterrupted or error-free access.
            We may update, modify, suspend, or discontinue features at any time without prior notice.
            In case of significant changes, users will be informed in advance.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">11. Limitation of Liability</h2>
          <p className="mb-4">To the fullest extent permitted by law:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Flow-XR shall not be liable for any indirect, incidental, or consequential damages arising from the use or inability to use the App.</li>
            <li>We are not responsible for actions taken based on AI-generated suggestions or interpretations.</li>
            <li>The App is provided "as is", without warranties of accuracy or completeness.</li>
          </ul>
          <p className="mb-6">This limitation does not affect rights guaranteed by consumer protection laws.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">12. Termination</h2>
          <p className="mb-6">
            You may delete your account at any time from your user dashboard or by contacting <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>.
            We may suspend or terminate access if you violate these Terms or use the App unlawfully.
          </p>
          <p className="mb-6">Upon deletion, all personal data will be processed according to our Privacy Policy.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">13. Governing Law and Jurisdiction</h2>
          <p className="mb-6">
            These Terms are governed by the laws of <strong>Poland</strong> and <strong>European Union regulations</strong>.
            Any disputes shall be resolved by competent courts in Poland, unless otherwise required by mandatory local consumer law.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">14. Contact</h2>
          <p className="mb-6">
            If you have questions or concerns about these Terms, please contact:
            <br />
            📧 <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>
          </p>
        </div>
      )}

      {/* Polish Version */}
      {language === "pl" && (
        <div className="prose prose-lg max-w-none">
          <h1 className="text-3xl font-bold mb-4">🇵🇱 Regulamin korzystania z aplikacji Flow-XR</h1>
          <p className="text-sm text-gray-600 mb-8"><strong>Ostatnia aktualizacja:</strong> 14 października 2025 r.</p>

          <p className="mb-6">
            Witamy w <strong>Flow-XR</strong>, aplikacji internetowej prowadzonej przez <strong>Flow System Adam Grono</strong>, oferującej sesje coachingowe wspierane przez sztuczną inteligencję w obszarach rozwoju osobistego, duchowości, przywództwa i pokrewnych tematów („Aplikacja").
          </p>
          <p className="mb-6">
            Korzystając z Aplikacji, akceptujesz poniższy regulamin. Prosimy o dokładne zapoznanie się z jego treścią przed rozpoczęciem korzystania.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">1. Definicje</h2>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li><strong>Aplikacja</strong> – aplikacja internetowa Flow-XR dostępna pod adresem <a href="https://flow-xr.com" className="text-blue-600 underline">https://flow-xr.com</a>.</li>
            <li><strong>Użytkownik / Ty</strong> – każda osoba korzystająca z Aplikacji, zarówno zalogowana, jak i gościnna.</li>
            <li><strong>Konto</strong> – konto użytkownika utworzone za pomocą adresu e-mail lub logowania Google OAuth.</li>
            <li><strong>Usługi AI</strong> – odpowiedzi i interakcje generowane przez zewnętrzne modele sztucznej inteligencji (np. OpenAI).</li>
            <li><strong>My / Administrator</strong> – Flow System Adam Grono, Lesoka 2/4, 81-574 Gdynia, Polska, <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>.</li>
          </ul>

          <h2 className="text-2xl font-bold mt-8 mb-4">2. Akceptacja regulaminu</h2>
          <p className="mb-4">Korzystając z Aplikacji, oświadczasz, że:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>zapoznałeś się z treścią regulaminu i go akceptujesz,</li>
            <li>zobowiązujesz się do jego przestrzegania,</li>
            <li>masz ukończone 18 lat lub posiadasz pełną zdolność do czynności prawnych.</li>
          </ul>
          <p className="mb-6">Jeśli nie zgadzasz się z regulaminem, nie korzystaj z Aplikacji.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">3. Opis usług</h2>
          <p className="mb-4">
            Flow-XR zapewnia interaktywne doświadczenia coachingowe wspierane przez AI, służące refleksji i rozwojowi osobistemu.
            Niektóre funkcje wymagają rejestracji lub logowania przez Google OAuth.
          </p>
          <p className="mb-4">Aplikacja może obejmować:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>czat z asystentem AI,</li>
            <li>śledzenie postępów,</li>
            <li>zapis historii sesji,</li>
            <li>notatki użytkownika.</li>
          </ul>
          <p className="mb-6">
            Aplikacja <strong>nie stanowi formy terapii, porady psychologicznej ani medycznej</strong>. Ma wyłącznie charakter edukacyjny i rozwojowy.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">4. Obowiązki użytkownika</h2>
          <p className="mb-4">Użytkownik zobowiązuje się:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>korzystać z Aplikacji zgodnie z prawem i zasadami współżycia społecznego,</li>
            <li>nie udostępniać treści nielegalnych, obraźliwych lub szkodliwych,</li>
            <li>nie wykorzystywać Aplikacji do celów marketingowych, spamu ani automatycznego pobierania danych,</li>
            <li>chronić swoje dane logowania,</li>
            <li>nie wprowadzać danych wrażliwych ani poufnych.</li>
          </ul>
          <p className="mb-6">Użytkownik ponosi odpowiedzialność za działania wykonane z jego konta.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">5. Zastrzeżenie dotyczące treści generowanych przez AI</h2>
          <p className="mb-4">
            Aplikacja wykorzystuje publicznie dostępne modele AI (np. OpenAI) do generowania odpowiedzi coachingowych.
            Odpowiedzi te:
          </p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>są generowane automatycznie,</li>
            <li>mogą być niekompletne lub subiektywne,</li>
            <li>nie stanowią profesjonalnej porady psychologicznej, medycznej ani prawnej.</li>
          </ul>
          <p className="mb-6">
            Korzystaj z nich z zachowaniem własnego rozsądku i odpowiedzialności. Flow-XR nie ponosi odpowiedzialności za decyzje podjęte na ich podstawie.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">6. Rejestracja i bezpieczeństwo konta</h2>
          <p className="mb-4">Użytkownicy mogą rejestrować się poprzez:</p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>adres e-mail i hasło, lub</li>
            <li>uwierzytelnienie Google OAuth.</li>
          </ul>
          <p className="mb-6">
            Zobowiązujesz się do podawania prawdziwych danych, ochrony swojego konta i niezwłocznego zgłaszania naruszeń bezpieczeństwa na adres <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>.
          </p>
          <p className="mb-6">Administrator może zawiesić lub usunąć konto w przypadku naruszenia regulaminu lub przepisów prawa.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">7. Użytkownicy gościnni</h2>
          <p className="mb-6">
            Użytkownicy niezalogowani mają dostęp do ograniczonych funkcji Aplikacji.
            Postęp takich użytkowników identyfikowany jest przez tymczasowy identyfikator zapisany w przeglądarce (localStorage).
            Dane te nie pozwalają na identyfikację osoby i mogą być usunięte przez użytkownika w dowolnym momencie.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">8. Prawa autorskie</h2>
          <p className="mb-6">
            Wszelkie treści, w tym teksty, projekt graficzny, kod i znaki towarowe, stanowią własność <strong>Flow System Adam Grono</strong> lub licencjodawców.
          </p>
          <p className="mb-6">
            Użytkownik może korzystać z Aplikacji wyłącznie do celów osobistych i niekomercyjnych.
            Kopiowanie, modyfikowanie lub inżynieria wsteczna Aplikacji bez zgody Administratora jest zabroniona.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">9. Prywatność i ochrona danych</h2>
          <p className="mb-6">
            Korzystanie z Aplikacji podlega zasadom określonym w <a href="/privacy" className="text-blue-600 underline">Polityce Prywatności</a>.
            Korzystając z Aplikacji, wyrażasz zgodę na przetwarzanie danych osobowych zgodnie z tą polityką.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">10. Dostępność i zmiany</h2>
          <p className="mb-6">
            Dokładamy starań, aby Aplikacja działała stabilnie, jednak nie gwarantujemy nieprzerwanego dostępu.
            Możemy wprowadzać zmiany, aktualizacje lub czasowe przerwy w działaniu bez wcześniejszego powiadomienia.
            O istotnych zmianach poinformujemy użytkowników z wyprzedzeniem.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">11. Ograniczenie odpowiedzialności</h2>
          <p className="mb-4">W najszerszym zakresie dozwolonym przez prawo:</p>
          <ul className="list-disc pl-6 mb-6 space-y-2">
            <li>Flow-XR nie ponosi odpowiedzialności za szkody pośrednie, przypadkowe lub wynikowe związane z korzystaniem z Aplikacji,</li>
            <li>nie odpowiada za decyzje podejmowane na podstawie treści generowanych przez AI,</li>
            <li>Aplikacja jest udostępniana „tak jak jest" – bez gwarancji pełnej dokładności lub nieprzerwanego działania.</li>
          </ul>
          <p className="mb-6">Postanowienia te nie ograniczają praw konsumentów wynikających z obowiązujących przepisów.</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">12. Usunięcie konta</h2>
          <p className="mb-6">
            Użytkownik może w każdej chwili usunąć swoje konto z poziomu panelu lub kontaktując się z nami pod adresem <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>.
            Administrator może zawiesić konto w przypadku naruszenia regulaminu.
            Dane osobowe będą przetwarzane zgodnie z Polityką Prywatności.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">13. Prawo właściwe i jurysdykcja</h2>
          <p className="mb-6">
            Regulamin podlega prawu <strong>polskiemu</strong> oraz <strong>przepisom Unii Europejskiej</strong>.
            Spory będą rozstrzygane przez właściwe sądy w Polsce, chyba że przepisy bezwzględnie obowiązujące stanowią inaczej.
          </p>

          <h2 className="text-2xl font-bold mt-8 mb-4">14. Kontakt</h2>
          <p className="mb-6">
            W sprawach dotyczących regulaminu skontaktuj się z nami:
            <br />
            📧 <a href="mailto:admin@flow-xr.com" className="text-blue-600 underline">admin@flow-xr.com</a>
          </p>
        </div>
      )}
    </div>
  );
}


